services:
  - type: web
    name: rashfa
    env: php
    rootDir: backend
    plan: free
    buildCommand: composer install --no-dev && php artisan config:cache && php artisan route:cache
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
